### ISSUE TITLE
Large Fluid Solidifier accept 1 type of forms

### ISSUE THREAD

**Issue by nemo48rus** [GregTechCEu/Gregification#28]
![image](https://user-images.githubusercontent.com/106464618/174303952-744f9183-ddb5-4a8b-b019-bad2a629db22.png)
How to automate that mech with many forms, if fluid bus accept only liquids? Or idk - it have different inputs option?

**Comment by foxwhite25** [comment]
uh, have 2 machines?

**Comment by nemo48rus** [comment]
> uh, have 2 machines?

Sorry, Big Liquid hardener*

**Comment by nemo48rus** [comment]
No comments.
